on:
  release:
    types: [released]

jobs:
  test-templating:
    runs-on: ubuntu-latest
    steps:
      - name: just echo message
        run: >
            echo "We have a new ${{github.event.release.tag_name}} release of our ${{ fromJson('{ "drewkitch/deepdish-gelato-hotline": "Deepdish Gelato Hotline", "deepdish-gelato-hotline": "just the repo" }')[github.event.repository.full_name] }} SDK, version ${{ github.event.release.name }}!
            Check out the details here: ${{ github.event.release.html_url }}"
